## Numpy Library

NumPy (Numerical Python) is the foundational library for scientific computing in Python. It introduces a powerful, high-performance N-dimensional array object that replaces slow Python loops with fast, compiled C-code operations.

In [752]:
import numpy as np

* The heart of NumPy is the ndarray (N-dimensional array). It is a grid of values that must all be of the same data type (homogenous).

In [753]:
#1DArray
array1 = np.array([10,20,30])
array1

array([10, 20, 30])

In [754]:
#1DArray with String values
array2 = np.array([5,-7.4,'a',7.2])
array2

array(['5', '-7.4', 'a', '7.2'], dtype='<U32')

In [755]:
#2DArray
array3 = np.array([[2.4,3],[4.91,7],[0,-10]])
array3

array([[  2.4 ,   3.  ],
       [  4.91,   7.  ],
       [  0.  , -10.  ]])

* ndim is a built-in attribute of a NumPy array that returns the number of dimensions (also known as axes or rank) of that array.

In [756]:
array1.ndim

1

In [757]:
array3.ndim

2

* shape is a NumPy array attribute that returns a tuple showing the length of each dimension (axis) of the array.

In [758]:
array1.shape

(3,)

In [759]:
array2.shape

(4,)

In [760]:
#(3,2) means array has 3 rows and 2 columns
array3.shape

(3, 2)

* size is a NumPy array attribute that returns the total number of elements across all dimensions in an array.

In [761]:
array1.size

3

In [762]:
array3.size

6

* dtype (data type) is a NumPy array attribute that tells you the exact data type of the elements stored inside the array

In [763]:
array1.dtype

dtype('int64')

In [764]:
array2.dtype


dtype('<U32')

In [765]:
array3.dtype

dtype('float64')

* itemsize is a NumPy array attribute that returns the length of one array element in bytes.

In [766]:
array1.itemsize

8

In [767]:
array2.itemsize

128

In [768]:
array3.itemsize

8

* we can specify data type while creating array using dtype as an argument to array()

In [769]:
array4 = np.array([[1,2],[3,4]] , dtype = float)
array4


array([[1., 2.],
       [3., 4.]])

* Intrinsic Creation of an Array
zeroes() function , for example , creates a full array of zeroes with dimensions defined by the shape argument 

In [770]:
array5 = np.zeros((3,4),dtype = int)
array5

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

* Arrays initialized using 1

In [771]:
array6 = np.ones((3,2))
array6

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

* Creating array with numbers in a given range 

In [772]:
array7 = np.arange(6)
array7

array([0, 1, 2, 3, 4, 5])

In [773]:
#step size 2
array8 = np.arange(-2,24,2)
array8

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

* generating 2D array with arange() combined with reshape()

In [774]:
array9 = np.arange(0,12).reshape(3,4)
array9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [775]:
array91 = np.arange(0,12).reshape(3,2,2)
array91

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

* The numpy.linspace() function generates an array of evenly spaced numbers over a specified mathematical interval

In [776]:
array10 = np.linspace(0,10,5)
array10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [777]:
array11 = np.linspace(0,10,2)
array11

array([ 0., 10.])

In [778]:
array12 = np.linspace(0,10,3)
array12

array([ 0.,  5., 10.])

* random.random() generates an array with elements as specified in the argument

In [779]:
array13 = np.random.random(3)
array13

array([0.20460212, 0.03409198, 0.23768401])

In [780]:
array14 = np.random.random((3,3))
array14

array([[0.93864901, 0.37000712, 0.35559303],
       [0.11447508, 0.26158428, 0.1620599 ],
       [0.228172  , 0.50029385, 0.42738977]])

### Indexing , Slicing and Iterating an array

In [781]:
array15 = np.array([[-7,0,10,20],[-5,1,40,200],[-1,1,4,30]])
array15

array([[ -7,   0,  10,  20],
       [ -5,   1,  40, 200],
       [ -1,   1,   4,  30]])

In [782]:
#access all the elements in the 3rd column
array15[0:3,2]

array([10, 40,  4])

In [783]:
#access elements of 2nd and 3rd row from 1st and 2nd column
array15[1:3,0:2]

array([[-5,  1],
       [-1,  1]])

In [784]:
array_index = np.arange(24).reshape(6,4)
array_index

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [785]:
#get all the elements of 3rd and 4th row

array_index[2:4,0:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [786]:
array_index[1:4,0:3]

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [787]:
array_index[1,0:2]

array([4, 5])

In [788]:
array_index[4,2:4]

array([18, 19])

In [789]:
array15[1,:]

array([ -5,   1,  40, 200])

* np.arange() is a NumPy function that creates an array containing a sequence of evenly spaced values within a specified numerical range.

In [790]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [791]:
for i in a:
    print(i)

10
11
12
13
14
15


* reshape() is a NumPy function that changes the structure (dimensions and shape) of an array without altering its actual underlying data.

In [792]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [793]:
for row in A :
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [794]:
A[0:3,0:1]

array([[10],
       [13],
       [16]])

In [795]:
#Iterating element by element , by using the for loop on "A.flat"
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


* apply_along_axis() function applies a custom function to 1D slices of an array along a specific dimension (axis)

In [796]:

np.apply_along_axis(np.mean,axis=0,arr = A)

array([13., 14., 15.])

In [797]:
np.apply_along_axis(np.mean,axis=1,arr=A)

array([11., 14., 17.])

In [798]:
#user defined function
def foo(x):
    return x/2

np.apply_along_axis(foo,axis=1,arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [799]:
np.apply_along_axis(foo,axis=0,arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

* np.random.random() is a function in NumPy that returns random floating-point numbers in the half-open interval [0.0, 1.0). This means the generated numbers can include 0.0, but are always strictly less than 1.0.

In [800]:
A = np.random.random((4,4))
A

array([[0.05406397, 0.71022032, 0.21449147, 0.07565333],
       [0.33032106, 0.10630492, 0.59699   , 0.6251817 ],
       [0.3537538 , 0.83677858, 0.61238192, 0.53687793],
       [0.88060513, 0.18519466, 0.75764685, 0.71239349]])

In [801]:
A < 0.5

array([[ True, False,  True,  True],
       [ True,  True, False, False],
       [ True, False, False, False],
       [False,  True, False, False]])

In [802]:
A[A < 0.5]

array([0.05406397, 0.21449147, 0.07565333, 0.33032106, 0.10630492,
       0.3537538 , 0.18519466])

In [803]:
a = np.random.random(12)
a

array([0.8338099 , 0.8328103 , 0.4042222 , 0.62307268, 0.56935807,
       0.78298424, 0.15070625, 0.23210155, 0.04222412, 0.87099009,
       0.83423275, 0.83969427])

### Shape Manipulation - reshape()

In [804]:
A = a.reshape(3,4)
A

array([[0.8338099 , 0.8328103 , 0.4042222 , 0.62307268],
       [0.56935807, 0.78298424, 0.15070625, 0.23210155],
       [0.04222412, 0.87099009, 0.83423275, 0.83969427]])

###  Shape Manipulation - shape(), ravel()

In [805]:
#modifying shape
a.shape = (3,4)
a

C:\Users\Shreya Deshmukh\AppData\Local\Temp\ipykernel_20960\579402221.py:2: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  a.shape = (3,4)


array([[0.8338099 , 0.8328103 , 0.4042222 , 0.62307268],
       [0.56935807, 0.78298424, 0.15070625, 0.23210155],
       [0.04222412, 0.87099009, 0.83423275, 0.83969427]])

In [806]:
#2nd into 1d using Ravel
a = a.ravel()
a

array([0.8338099 , 0.8328103 , 0.4042222 , 0.62307268, 0.56935807,
       0.78298424, 0.15070625, 0.23210155, 0.04222412, 0.87099009,
       0.83423275, 0.83969427])

In [807]:
x = np.arange(1,25)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

*ravel() is a NumPy function that flattens a multi-dimensional array into a continuous, 1D vector.

In [808]:
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [809]:
x.shape = (4,6)
x

C:\Users\Shreya Deshmukh\AppData\Local\Temp\ipykernel_20960\1849622746.py:1: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  x.shape = (4,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [810]:
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [811]:
a.shape = (12)
a

C:\Users\Shreya Deshmukh\AppData\Local\Temp\ipykernel_20960\4229885536.py:1: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  a.shape = (12)


array([0.8338099 , 0.8328103 , 0.4042222 , 0.62307268, 0.56935807,
       0.78298424, 0.15070625, 0.23210155, 0.04222412, 0.87099009,
       0.83423275, 0.83969427])

In [812]:
array16 = np.array([[3,6] , [4,2]])
array16

array([[3, 6],
       [4, 2]])

In [813]:
array17 = np.array([[10,20],[15,12]])
array17

array([[10, 20],
       [15, 12]])

### Basic Operations on Arrays - Arithmetic Operations

In [814]:
#Element wise addition of two matrics
array16 + array17

array([[13, 26],
       [19, 14]])

In [815]:
#Element-wise substraction of two matrices
array16 - array17

array([[ -7, -14],
       [-11, -10]])

In [816]:
#Element-wise multiplication of two matrices
array16 * array17

array([[ 30, 120],
       [ 60,  24]])

In [817]:
#Matrix Multiplication of two matrices
array16 @ array17

array([[120, 132],
       [ 70, 104]])

In [818]:
#Element-wise exponentiation of two matrices
array16 ** 3

array([[ 27, 216],
       [ 64,   8]])

In [819]:
#Element-wise remainder of division (modulo)
array17 % array16

array([[1, 2],
       [3, 0]])

### Basic Operations on Arrays - Increment and Decrement Operators

In [820]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [821]:
a += 1
a

array([1, 2, 3, 4])

In [822]:
a -= 1
a

array([0, 1, 2, 3])

In [823]:
a +=4
a

array([4, 5, 6, 7])

In [824]:
a *= 2
a

array([ 8, 10, 12, 14])

### Basic Operations on Arrays - The Matrix Product - dot() function

In [825]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [826]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [827]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [828]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [829]:
#transpose()
array18 = np.array([[10,-7,0,20],[-5,1,200,40],[30,1,-1,4]])
array18

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [830]:
array18.transpose()

array([[ 10,  -5,  30],
       [ -7,   1,   1],
       [  0, 200,  -1],
       [ 20,  40,   4]])

In [831]:
#original array does not change
array18

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

### Basic Operations on Arrays - sort()

In [832]:
array19 = np.array([1,0,2,-3,6,8,4,7])
array19

array([ 1,  0,  2, -3,  6,  8,  4,  7])

In [833]:
array19.sort()
array19

array([-3,  0,  1,  2,  4,  6,  7,  8])

In [834]:
array20 = np.array([[10,-7,0,20],[-5,1,200,40],[30,1,-1,4]])
array20

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [835]:
array20.sort()
array20

array([[ -7,   0,  10,  20],
       [ -5,   1,  40, 200],
       [ -1,   1,   4,  30]])

### Basic Operations on Arrays - concatenate()

In [836]:
array22 = np.array([[10,20],[-30,40]])
array22

array([[ 10,  20],
       [-30,  40]])

In [837]:
array23 = np.zeros((2,3),dtype=array22.dtype)
array23

array([[0, 0, 0],
       [0, 0, 0]])

In [838]:
array22.shape

(2, 2)

In [839]:
array23.shape

(2, 3)

In [840]:
#concatenate along axis =
np.concatenate((array22,array23),axis = 1)

array([[ 10,  20,   0,   0,   0],
       [-30,  40,   0,   0,   0]])

In [841]:
x = np.arange(4).reshape(2,2)
y = np.ones(4).reshape(2,2)

In [842]:
x

array([[0, 1],
       [2, 3]])

In [843]:
y

array([[1., 1.],
       [1., 1.]])

In [844]:
np.concatenate((x,y))

array([[0., 1.],
       [2., 3.],
       [1., 1.],
       [1., 1.]])

### Basic Operations on Arrays - vstack(), hstack() - Joining

* All the dimensions of the array to be concatenated must match exactly

* vstack - stacks array vertically (row-wise) , 
* htsack - stacks array horizontally (column-wise) .

In [845]:
A = np.ones((3,3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [846]:
B = np.zeros((3,3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [847]:
np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [848]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

* column_stack() alias for hstack
* row_stack() alias for vstack 

In [849]:
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])

In [850]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [851]:
np.row_stack((a,b,c))

AttributeError: module 'numpy' has no attribute 'row_stack'

* The AttributeError: module 'numpy' has no attribute 'row_stack' occurs because np.row_stack has been officially deprecated and completely removed from modern versions of NumPy.

* NumPy clean-up updates removed redundant and duplicate "alias" functions. Because row_stack and vstack did the exact same thing behind the scenes, the creators kept only np.vstack to make the library cleaner and faster.

* While np.row_stack was purely a "useless duplicate" of np.vstack, np.column_stack actually does something completely different from its horizontal sibling, np.hstack, when given 1D arrays

### Basic Operations on Arrays - split()
* The numpy.split() function divides a NumPy array into multiple sub-arrays along a specified axis. It requires that the array be split into equally sized parts; otherwise, it throws a ValueError

In [ ]:
array24 = np.array([[10,-7,0,20],[-5,1,200,40],[30,1,-1,4],[1,2,0,4],[0,1,0,2]])
array24

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4],
       [  1,   2,   0,   4],
       [  0,   1,   0,   2]])

In [ ]:
#[1,3] indicates the row indices on which to split the array , By default , axis = 0
first , second , third = np.split(array24,[1,3])
print("first = \n" , first)
print("second = \n" , second)
print("third = \n" , third)

first = 
 [[10 -7  0 20]]
second = 
 [[ -5   1 200  40]
 [ 30   1  -1   4]]
third = 
 [[1 2 0 4]
 [0 1 0 2]]


In [ ]:
first , second , third = np.split(array24,[3,4],axis = 1)
print("first = \n" , first)
print("second = \n" , second)
print("third = \n" , third)


first = 
 [[ 10  -7   0]
 [ -5   1 200]
 [ 30   1  -1]
 [  1   2   0]
 [  0   1   0]]
second = 
 [[20]
 [40]
 [ 4]
 [ 4]
 [ 2]]
third = 
 []


In [ ]:
# 2nd parameter 2 implies array is to be split in 2 equal parts over
# axis=1 along the column axis

firsthalf , secondhalf = np.split(array24,2,axis = 1)
print("first = \n" , firsthalf)
print("second = \n" , secondhalf)

first = 
 [[10 -7]
 [-5  1]
 [30  1]
 [ 1  2]
 [ 0  1]]
second = 
 [[  0  20]
 [200  40]
 [ -1   4]
 [  0   4]
 [  0   2]]


* np.vsplit (Vertical Split) cuts your data horizontally like a knife, slicing it into row blocks.

* np.hsplit (Horizontal Split) cuts your data vertically like a knife, slicing it into column blocks.

* np.dsplit (Depth Split) slices 3D arrays along the third axis (depth)

In [ ]:
a = np.arange(16.0).reshape(4,4)
a

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
np.hsplit(a,2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [ ]:
np.hsplit(a,np.array([2,3]))

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.],
        [ 6.],
        [10.],
        [14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]])]

In [ ]:
b = np.arange(20.0).reshape(4,5)
b

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [ ]:
np.vsplit(b,2)

[array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]),
 array([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])]

In [ ]:
np.vsplit(b, np.array([1, 3]))

[array([[0., 1., 2., 3., 4.]]),
 array([[ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]]),
 array([[15., 16., 17., 18., 19.]])]

In [ ]:
c = np.arange(12.0).reshape (2,2,3)
c

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [ ]:
np.dsplit(c,3)

[array([[[0.],
         [3.]],
 
        [[6.],
         [9.]]]),
 array([[[ 1.],
         [ 4.]],
 
        [[ 7.],
         [10.]]]),
 array([[[ 2.],
         [ 5.]],
 
        [[ 8.],
         [11.]]])]

In [ ]:
np.dsplit(c, np.array([1,3]))

[array([[[0.],
         [3.]],
 
        [[6.],
         [9.]]]),
 array([[[ 1.,  2.],
         [ 4.,  5.]],
 
        [[ 7.,  8.],
         [10., 11.]]]),
 array([], shape=(2, 2, 0), dtype=float64)]

### Statistical Operations on Arrays

In [ ]:
arrayA = np.array([1,0,2,-3,6,8,4,7])
arrayA

array([ 1,  0,  2, -3,  6,  8,  4,  7])

In [ ]:
arrayB = np.array([[3,6],[4,2]])
arrayB

array([[3, 6],
       [4, 2]])

* finds the largest numerical value in an array

In [ ]:
arrayA.max()

np.int64(8)

In [ ]:
arrayB.max()

np.int64(6)

In [ ]:
arrayB.max(axis = 1)

array([6, 4])

In [ ]:
arrayB.max(axis = 0)

array([4, 6])

* finds the smallest numerical value in an array.

In [ ]:
arrayB.min(axis = 0)

array([3, 2])

* adds numerical values in an array together. 

In [ ]:
arrayA.sum()

np.int64(25)

*  operation calculates the arithmetic average of an array by summing all elements and dividing by the total number of items.

In [ ]:
arrayA.mean()

np.float64(3.125)

In [ ]:
arrayB.mean(axis=0)

array([3.5, 4. ])

* The standard deviation (std) measures the amount of variation or dispersion in a dataset.

In [ ]:
arrayA.std()

np.float64(3.550968177835448)

In [ ]:
arrayB.std(axis=0)

array([0.5, 2. ])

In [ ]:
np.std(arrayB,axis=0)

array([0.5, 2. ])

*  finds the middle value of an array after sorting the elements in ascending order.

In [ ]:
np.median(arrayB , axis=1)

array([4.5, 3. ])

* The variance (var) measures the average squared distance of data points from their arithmetic mean. 

In [ ]:
arrayA.var()

np.float64(12.609375)

In [ ]:
arrayB.var(axis=0)

array([0.25, 4.  ])

* The ptp() peak-to-peak function finds a range of values along an axis.


In [ ]:
arrayA.ptp()

# This error occurs because the .ptp() method was permanently removed from the array class (numpy.ndarray) in NumPy 2.0.To fix it immediately, 
# you need to use the standalone function np.ptp(arrayA) instead of calling it as a method on the array.

AttributeError: 'numpy.ndarray' object has no attribute 'ptp'

In [ ]:
np.ptp(arrayA)

np.int64(11)

* The percentile operation finds the value below which a given percentage of data falls. For example, the 50th percentile is the median.

In [ ]:
np.percentile(arrayA,50,0)

np.float64(3.0)

In [ ]:
np.percentile(arrayB,50,1) #50th percentile along axis = 1

array([4.5, 3. ])

In [ ]:
array100 = np.arange(100).reshape(10,10)
array100

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

* The save operation writes array data or statistical results to a permanent storage file on your disk

In [ ]:
np.save('saved_data',array100)

* The load operation reads previously saved array data or statistical models from your disk storage back into your active program memory.

In [ ]:
loaded_data = np.load('saved_data.npy')
loaded_data

* The np.loadtxt() function is a fast, efficient NumPy utility used to parse and load numerical data from plain text or CSV files directly into a NumPy array.

In [ ]:
sampleData = np.loadtxt('SampleData.txt', skiprows = 1, delimiter=',', dtype=int)
sampleData

In [ ]:
C1, C2, C3 = np.loadtxt('SampleData.txt', skiprows=1, delimiter=',', dtype=int)

In [ ]:
C1

In [ ]:
C2

* The np.savetxt() function is a built-in NumPy utility used to export array data from your program memory into a formatted, human-readable plain text or CSV file.

In [ ]:
np.savetxt("output.txt", C2, delimiter = ',', fmt="%i")